name: 'Annotate JUnit XML build results'
description: 'Annotate JUnit XML build results on GitHub Actions build'
branding:
  icon: 'box'  
  color: 'green'
inputs:
  githubToken:
    description: 'github token'
    required: true
  projectPath:
    description: 'Path to server project'
    required: true
    default: 'service/server'
  junitSubPath:
    description: 'Glob path to JUnit XML files inside project'
    required: true
    default: 'build/test-results/test/*.xml'
  testSrcSubPath:
    description: 'Path to test source files inside project'
    required: true
    default: 'src/test/kotlin/'
  maxFailures:
    description: 'Maximum amount of failed tests to include'
    required: true
    default: '10'
  jobName:
    description: 'Partial match of job name to annotate in this workflow'
    required: true
    default: 'test-server'

runs:
  using: 'node12'
  main: 'dist/index.js'
